import type { Metadata } from "next";
//apagar segunda linha (import)
import "./globals.css";

//apagar da linha 4 a 12

export const metadata: Metadata = {
  title: "Primero porjeto", //título da página (lá em cimão)
  description: "Generated by create next app", //descricao do projeto
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        {children}
      </body>
    </html>
  );
}